imagemagick: fix linking of host libfreetype
Host's libfreetype is being linked during build.

libtool: warning: relinking 'MagickWand/libMagickWand-7.Q8.la'
libtool: install: (cd /home/egorenar/Repositories/openwrt-rel/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ImageMagick-7.0.9-5; /bin/sh "/home/egorenar/Repositories/openwrt-rel/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ImageMagick-7.0.9-5/libtool"  --tag CC --mode=relink arm-openwrt-linux-muslgnueabi-gcc -I/home/egorenar/Repositories/openwrt-rel/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/usr/include/libpng16 -I/home/egorenar/Repositories/openwrt-rel/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/usr/include -I/home/egorenar/Repositories/openwrt-rel/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/usr/include/freetype2 -I/home/egorenar/Repositories/openwrt-rel/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/usr/include -I/home/egorenar/Repositories/openwrt-rel/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/usr/include/libpng16 -I/home/egorenar/Repositories/openwrt-rel/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/usr/include -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/home/egorenar/Repositories/openwrt-rel/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ImageMagick-7.0.9-5=ImageMagick-7.0.9-5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -flto -Wall -fexceptions -pthread -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=8 -no-undefined -Wl,--version-script=./MagickWand/libMagickWand.map -version-info 7:0:0 -L/home/egorenar/Repositories/openwrt-rel/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.4.0_musl_eabi/usr/lib -L/home/egorenar/Repositories/openwrt-rel/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.4.0_musl_eabi/lib -znow -zrelro -o MagickWand/libMagickWand-7.Q8.la -rpath /usr/lib MagickWand/libMagickWand_7_Q8_la-animate.lo MagickWand/libMagickWand_7_Q8_la-compare.lo MagickWand/libMagickWand_7_Q8_la-composite.lo MagickWand/libMagickWand_7_Q8_la-conjure.lo MagickWand/libMagickWand_7_Q8_la-convert.lo MagickWand/libMagickWand_7_Q8_la-deprecate.lo MagickWand/libMagickWand_7_Q8_la-display.lo MagickWand/libMagickWand_7_Q8_la-drawing-wand.lo MagickWand/libMagickWand_7_Q8_la-identify.lo MagickWand/libMagickWand_7_Q8_la-import.lo MagickWand/libMagickWand_7_Q8_la-magick-cli.lo MagickWand/libMagickWand_7_Q8_la-magick-image.lo MagickWand/libMagickWand_7_Q8_la-magick-property.lo MagickWand/libMagickWand_7_Q8_la-magick-wand.lo MagickWand/libMagickWand_7_Q8_la-mogrify.lo MagickWand/libMagickWand_7_Q8_la-montage.lo MagickWand/libMagickWand_7_Q8_la-operation.lo MagickWand/libMagickWand_7_Q8_la-pixel-iterator.lo MagickWand/libMagickWand_7_Q8_la-pixel-wand.lo MagickWand/libMagickWand_7_Q8_la-script-token.lo MagickWand/libMagickWand_7_Q8_la-stream.lo MagickWand/libMagickWand_7_Q8_la-wand.lo MagickWand/libMagickWand_7_Q8_la-wandcli.lo MagickWand/libMagickWand_7_Q8_la-wand-view.lo MagickCore/libMagickCore-7.Q8.la -lm -inst-prefix-dir /home/egorenar/Repositories/openwrt-rel/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ImageMagick-7.0.9-5/ipkg-install)
libtool: relink: arm-openwrt-linux-muslgnueabi-gcc -shared  -fPIC -DPIC  MagickWand/.libs/libMagickWand_7_Q8_la-animate.o MagickWand/.libs/libMagickWand_7_Q8_la-compare.o MagickWand/.libs/libMagickWand_7_Q8_la-composite.o MagickWand/.libs/libMagickWand_7_Q8_la-conjure.o MagickWand/.libs/libMagickWand_7_Q8_la-convert.o MagickWand/.libs/libMagickWand_7_Q8_la-deprecate.o MagickWand/.libs/libMagickWand_7_Q8_la-display.o MagickWand/.libs/libMagickWand_7_Q8_la-drawing-wand.o MagickWand/.libs/libMagickWand_7_Q8_la-identify.o MagickWand/.libs/libMagickWand_7_Q8_la-import.o MagickWand/.libs/libMagickWand_7_Q8_la-magick-cli.o MagickWand/.libs/libMagickWand_7_Q8_la-magick-image.o MagickWand/.libs/libMagickWand_7_Q8_la-magick-property.o MagickWand/.libs/libMagickWand_7_Q8_la-magick-wand.o MagickWand/.libs/libMagickWand_7_Q8_la-mogrify.o MagickWand/.libs/libMagickWand_7_Q8_la-montage.o MagickWand/.libs/libMagickWand_7_Q8_la-operation.o MagickWand/.libs/libMagickWand_7_Q8_la-pixel-iterator.o MagickWand/.libs/libMagickWand_7_Q8_la-pixel-wand.o MagickWand/.libs/libMagickWand_7_Q8_la-script-token.o MagickWand/.libs/libMagickWand_7_Q8_la-stream.o MagickWand/.libs/libMagickWand_7_Q8_la-wand.o MagickWand/.libs/libMagickWand_7_Q8_la-wandcli.o MagickWand/.libs/libMagickWand_7_Q8_la-wand-view.o   -L/home/egorenar/Repositories/openwrt-rel/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.4.0_musl_eabi/usr/lib -L/home/egorenar/Repositories/openwrt-rel/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.4.0_musl_eabi/lib -L/home/egorenar/Repositories/openwrt-rel/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ImageMagick-7.0.9-5/ipkg-install/usr/lib -L/usr/lib -lMagickCore-7.Q8 -L/home/egorenar/Repositories/openwrt-rel/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/usr/lib -lfreetype -lz -lltdl -lm  -Os -mfloat-abi=hard -fstack-protector -Wl,-z -Wl,now -Wl,-z -Wl,relro -flto -pthread -Wl,--version-script=./MagickWand/libMagickWand.map   -pthread -Wl,-soname -Wl,libMagickWand-7.Q8.so.7 -o MagickWand/.libs/libMagickWand-7.Q8.so.7.0.0
/usr/lib/libfreetype.so: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'MagickWand/libMagickWand-7.Q8.la' with the above command before installing it
make[5]: *** [Makefile:6264: install-libLTLIBRARIES] Error 1
make[5]: Leaving directory '/home/egorenar/Repositories/openwrt-rel/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ImageMagick-7.0.9-5'
make[4]: *** [Makefile:12263: install-am] Error 2
make[4]: Leaving directory '/home/egorenar/Repositories/openwrt-rel/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ImageMagick-7.0.9-5'
make[3]: *** [Makefile:12257: install] Error 2
make[3]: Leaving directory '/home/egorenar/Repositories/openwrt-rel/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ImageMagick-7.0.9-5'
make[2]: *** [Makefile:153: /home/egorenar/Repositories/openwrt-rel/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ImageMagick-7.0.9-5/.built] Error 2
make[2]: Leaving directory '/home/egorenar/Repositories/openwrt-rel/feeds/packages/multimedia/imagemagick'
time: package/feeds/packages/imagemagick/compile#105.77#18.23#212.14
    ERROR: package/feeds/packages/imagemagick failed to build.
make[1]: *** [package/Makefile:114: package/feeds/packages/imagemagick/compile] Error 1
make[1]: Leaving directory '/home/egorenar/Repositories/openwrt-rel'
make: *** [/home/egorenar/Repositories/openwrt-rel/include/toplevel.mk:230: package/imagemagick/compile] Error 2

Signed-off-by: Alexander Egorenkov <egorenar-dev@posteo.net>